nelmio_api_doc:
    documentation:
        info:
            title: Test API
            description: Test API
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api(?!/doc$)
