services:
    nginx:
        build:
          context: docker/nginx
        container_name: nginx_test
        volumes:
            - .:/var/www:rw
        ports:
            - ${NGINX_PORT}:80
        restart: always
        depends_on:
            - php
            - postgres
    php:
        build:
          context: docker/php
        container_name: php_test
        restart: always
        volumes:
            - .:/var/www
    postgres:
        build:
          context: docker/postgres
        container_name: postgres_test
        restart: always
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        ports:
            - ${POSTGRES_PORT}:5432
        volumes:
            - ./docker/postgres/data:/var/lib/postgresql/data
